#!/bin/bash

## more or less copied from [autorandr](https://github.com/wertarbyte/autorandr)
detect_display()
{
	## iterate for X11 sockets
	for X in /tmp/.X11-unix/X*; do
		## get user owning the socket
		D="${X##/tmp/.X11-unix/X}"
		user=$(who | awk -vD="$D" '$5 ~ "\\(:"D"\\)$" {print $1}')
		## run autoxbkmap for that user (if the file is executable)
		if [ x"${user}" != x"" ] && [ -x "/home/${user}/.config/autoxkbmap" ]; then
			export DISPLAY=":$D"
			echo "running autoxkbmap for ${user} on display ${DISPLAY}"
			/bin/su -c "/home/${user}/.config/autoxkbmap" "${user}"
		fi
	done
}

## lets wait for the system to settel
sleep 3
## and then run autoxkbmap for every user with an X11 session
detect_display
